USE [PRD_xlinedta001_001]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A_DOCUMENT_INDEX](
	[ID] INT IDENTITY(1,1) PRIMARY KEY, 
	[DD1rA] [varchar](12) NULL,
	[DDr68A] [char](1) NULL
) ON [PRIMARY]
GO
CREATE INDEX IDX_DD1rA ON A_DOCUMENT_INDEX (DD1rA);
GO
CREATE INDEX IDX_DDr68A ON A_DOCUMENT_INDEX (DDr68A);
GO


CREATE TABLE [dbo].[A_FOLDER_INDEX](
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[folderId] [numeric](15, 0) NULL,
	[status] [char](1) NULL
) ON [PRIMARY]
GO
CREATE INDEX IDX_folderId ON A_FOLDER_INDEX (folderId);
GO
CREATE INDEX IDX_status ON A_FOLDER_INDEX (status);
GO