CREATE TABLE [dbo].[A_DOCUMENT_INDEX](
	[ID] INT IDENTITY(1,1) PRIMARY KEY, 
	[DD1rA] [varchar](12) NULL,
	[DDr68A] [char](1) NULL
) ON [PRIMARY]
GO
CREATE INDEX IDX_A_DOCUMENT_INDEX_1rA ON A_DOCUMENT_INDEX (DD1rA);
GO
CREATE INDEX IDX_A_DOCUMENT_INDEX_68A ON A_DOCUMENT_INDEX (DDr68A);
GO


CREATE TABLE [dbo].[A_FOLDER_INDEX](
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[folderId] [numeric](15, 0) NULL,
	[status] [char](1) NULL
) ON [PRIMARY]
GO
CREATE INDEX IDX_A_FOLDER_INDEX_fId ON A_FOLDER_INDEX (folderId);
GO
CREATE INDEX IDX_A_FOLDER_INDEX_sts ON A_FOLDER_INDEX (status);
GO