; ==========================================================
; Fichier de configuration de traitement configuration
; ==========================================================
; Ce fichier contient les paramètres de configuration pour
; la connexion à la base de données SQL Server et à Solr,
; ainsi que les paramètres de traitement.
; ==========================================================

[logging]
; activation des logs 
enable_logging=false
log_folder=D:\PYTHON\indexsolrrapide\test\logs
; activation des affichages détaillés 
enable_print=true
[SGBD]
; paramétrage de la base de données mettre (SQL ou DB2)
# db_type=DB2
# db_driver=iSeries access ODBC Driver
# ou
# db_type=SQL
# db_driver=ODBC Driver 18 for SQL Server
db_type=SQL
db_driver=ODBC Driver 18 for SQL Server
db_server=YDGLUVA2022
db_port=1433
db_username=sa_PRD
db_password=passwordT2I
db_database=PRD_xlinedta001_001
[SOLR]
; paramétrage SOLR
solr_hostname=ydgluva2022:8984
solr_username=prd-dft-svc
solr_password=prddftsvcT2I
solr_tenant=001
[traitement]
; nombre d'entree teste par lot
traitement_lot=80000
; pause après le lot en secondes
traitement_pause=300
; perimetre de traitement (DOCUMENT ou FOLDER)
traitement_type=DOCUMENT