[SERVICE]
NOM_SERVICE=Youdoc_Synchro
SERVICE_HEURE=*
SERVICE_MINUTE=*

[ENVIRONNEMENT]
CLIENT=LAINX
ENVIRONNEMENT=VM

[KEYCLOAK]
KEYCLOAK_URL=https://ydgluva24q:8281
KEYCLOAK_CLIENTSECRET = k42xJ7DrVT6lW9l8nDorRtc64mL6l76c
KEYCLOAK_LOGIN=administrateur
KEYCLOAK_PASSWORD=toor

[YOUDOC]
YOUDOC_URL = https://ydgluva24q:8443
YOUDOC_TENANT = 001
YOUDOC_LOGIN = lainxluva
YOUDOC_PASSWORD = passwordT2I

[SOLR]
SOLR_URL=https://YDGLUVA24Q:8984
; SOLR_LOGIN=default-svc-usr
; SOLR_PASSWORD=zYDdjrIZ2M1jbgv
SOLR_LOG=True

[PARAM]
KEYCLOAK_TIMEOUT_TIME = 1
KEYCLOAK_VERIF_SSL = False
YOUDOC_TIMEOUT_TIME = 1
YOUDOC_VERIF_SSL = False
SOLR_TIMEOUT_TIME = 1
SOLR_VERIF_SSL = False