[SGBD]
# SQL ou DB2
DB_type=SQL		 
# ODBC Driver 18 for SQL Server ou iSeries access ODBC Driver
DB_driver=ODBC Driver 18 for SQL Server
DB_server=YDGLUVA24Q
DB_port=1433
DB_username=SA_PRD
DB_password=passwordT2I
DB_database=PRD_YDG_001


[FOLDER]
DB_data_fold=A_LISTE_FOL
DB_name_fold=EZBUNU
DB_name_status=STATUS
Lot_fold=1

[DOCUMENT]
DB_data_docactive=True
DB_data_doc=A_LISTE_DOC
DB_name_docfold=EZBUNU
DB_name_doc=DOCID
DB_name_docstatus=DDR68A


[SOLR]
# paramétrage SOLR
SOLR_hostname=YDGLUVA24Q:8984
SOLR_username=default-svc-usr
SOLR_password=zYDdjrIZ2M1jbgv
SOLR_tenant=001
VERIF_SSL=False

[LUVA]
DEBUG=True
IS_DEBUG=False