CREATE TABLE A_DOCUMENT_INDEX (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    DD1rA VARCHAR(12),
    DDr68A CHAR(1)
);
-- Index sur la colonne DD1RA
CREATE INDEX IDX_DD1RA
    ON A_DOCUMENT_INDEX (DD1RA);

-- Index sur la colonne DDR68A
CREATE INDEX IDX_DDR68A
    ON A_DOCUMENT_INDEX (DDR68A);


CREATE TABLE A_FOLDER_INDEX (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    folderId numeric(15, 0),
    status char(1)
);
-- Index sur la colonne DD1RA
CREATE INDEX IDX_folderId
    ON A_FOLDER_INDEX (folderId);

-- Index sur la colonne DDR68A
CREATE INDEX IDX_status
    ON A_FOLDER_INDEX (status);
