; ==========================================================
; Fichier de configuration de traitement configuration
; ==========================================================
; Ce fichier contient les paramètres de configuration pour
; la connexion à la base de données SQL Server et à Solr,
; ainsi que les paramètres de traitement.
; ==========================================================

[SGBD]
# SQL ou DB2
db_type=SQL
# ODBC Driver 18 for SQL Server ou iSeries access ODBC Driver
db_driver=ODBC Driver 18 for SQL Server
db_server=YDGLUVA24Q
db_port=1433
db_username=sa_PRD
db_password=passwordT2I
db_database=PRD_YDG_003

[logging]
enable_logging=FALSE
log_folder=D:\PYTHON\YouDoc_PAC\test\logs
log_event_level=DEBUG
log_folder_level=INFO
log_console_level=DEBUG

[PAC]
parameter_file=D:\PYTHON\YouDoc_PAC\test\XpertECM.PAC.YDGLUVA24Q.PRD_YDG_003.ENV003.xml

[AUTRES]
langue=FR