; ==========================================================
; Fichier de configuration de traitement configuration
; ==========================================================
; Ce fichier contient les paramètres de configuration pour
; la connexion à la base de données SQL Server et à Solr,
; ainsi que les paramètres de traitement.
; ==========================================================

[SGBD]
# SQL ou DB2
db_type=SQL		 
# ODBC Driver 18 for SQL Server ou iSeries access ODBC Driver
db_driver=ODBC Driver 18 for SQL Server
db_server=YDGLUVA2022
db_port=1433
db_username=sa_PRD
db_password=passwordT2I
db_database=PRD_xlinedta001_001
db_log=D:\PYTHON\YouDoc_Entretien\test\logs
db_log_level=DEBUG

[SOLR]
# paramétrage SOLR
solr_hostname=ydgluva2022:8984
solr_username=prd-dft-svc
solr_password=prddftsvcT2I
solr_tenant=001