; ==========================================================
; Fichier de configuration de traitement configuration
; ==========================================================
; Ce fichier contient les paramètres de configuration pour
; la connexion à la base de données SQL Server et à Solr,
; ainsi que les paramètres de traitement.
; ==========================================================

[logging]
log_console_level=DEBUG

[param]
PROCESSUS=CACERTS
DOSSIER_EXPORT=D:\PYTHON\Luva_cert\TEST\CACERTS\
DOSSIER_CRT=D:\PYTHON\Luva_cert\TEST\CRT\

[certif]
PFX_PASSWORD=changeit