[ENVIRONNEMENT]
CLIENT=LAINX
ENVIRONNEMENT=VM

[KEYCLOAK]
KEYCLOAK_URL=https://ydgluva24q:8281
KEYCLOAK_CLIENTSECRET = k42xJ7DrVT6lW9l8nDorRtc64mL6l76c
KEYCLOAK_LOGIN=administrateur
KEYCLOAK_PASSWORD=toor

[KEYCLOAK_PARAM]
KEYCLOAK_TIMEOUT_TIME = 10
KEYCLOAK_VERIF_SSL = False
KEYCLOAK_CREATE_ROLE = True
GENERATION_RAPPORT=True

[EXCEL]
EXCEL_FICHIER=D:\PYTHON\Youdoc_Keycloak_creator\2\dist\YoudocFichier.xlsx

[YOUDOC]
YOUDOC_URL = https://ydgluva24q:8443
YOUDOC_TENANT = 001
YOUDOC_LOGIN = lainxluva
YOUDOC_PASSWORD = passwordT2I



[YOUDOC_PARAM]
TIMEOUT_TIME = 10
VERIF_SSL = False
YOUDOC_CREATE_GROUPE = True
GENERATION_RAPPORT=True

[IDP]
CREATE_MAPPER = True
GENERATION_RAPPORT=True

[LUVA]
ACTION=SUPPRESSION
; DEBUG=True
; IS_DEBUG=True
; CALCUL_CLIENT_REALM=YD-LAINX-VM
; CALCUL_CLIENT=YDG-LAINX-VM
; EXCEL_FEUILLE_YDG=YDG_ENTRA_ID
; EXCEL_APPLICATION=ydg
; EXCEL_FIRST=14
; IDP_ALIAS=TEST