; ==========================================================
; Fichier de configuration de traitement configuration
; ==========================================================
; Ce fichier contient les paramètres de configuration pour
; la connexion à la base de données SQL Server et à Solr,
; ainsi que les paramètres de traitement.
; ==========================================================

[logging]
log_console_level=DEBUG


[param]
PROCESSUS=EXTRACTION

[certif]
COMMON_NAME=TEST
NB_BITS=2048
JOURS=365
DNS=TEST1,TEST2,TEST3,localhost
IP=000.000.000.000
PFX_GEN=TRUE
PFX_PASSWORD=changeit