[SGBD]
# SQL ou DB2
DB_type=SQL		 
# ODBC Driver 18 for SQL Server ou iSeries access ODBC Driver
DB_driver=ODBC Driver 18 for SQL Server
DB_server=YDGLUVA24Q
DB_port=1433
DB_username=SA_PRD
DB_password=passwordT2I
DB_database=PRD_YDG_001

[SOLR]
# paramétrage SOLR
SOLR_hostname=YDGLUVA24Q:8984
SOLR_username=default-svc-usr
SOLR_password=zYDdjrIZ2M1jbgv
SOLR_tenant=001
VERIF_SSL=False

[INPUT]
TYPE_DOC=IXX
ECM_IXX_INPUT=\\nas-0301\mdsa142_ppr_dataexternal\001\xecm\ixx
ECM_IXX_ERROR=\\nas-0301\mdsa142_ppr_dataexternal\001\xecm\ixx\error
ECM_IXX_OUTPUT=\\nas-0301\mdsa142_ppr_dataexternal\001\xecm\ixx\output
ECM_IXX_WORKING=\\nas-0301\mdsa142_ppr_dataexternal\001\xecm\ixx\working

[PARAM]
PARAM_TIME=30

[LUVA]
DEBUG=True
IS_DEBUG=False