[SGBD]
# SQL ou DB2
DB_type=SQL		 
# ODBC Driver 18 for SQL Server ou iSeries access ODBC Driver
DB_driver=ODBC Driver 18 for SQL Server
DB_server=YDGLUVA24Q
DB_port=1433
DB_username=SA_PRD
DB_password=passwordT2I
DB_database=PRD_YDG_001
DB_data=A_LISTE_DOC
DB_name=DOCID

[SOLR]
# paramétrage SOLR
SOLR_hostname=YDGLUVA24Q:8984
SOLR_username=default-svc-usr
SOLR_password=zYDdjrIZ2M1jbgv
SOLR_tenant=001
SOLR_requete=XECM-DOCUMENT--
SOLR_lot=20
VERIF_SSL=False

[LUVA]
DEBUG=True
IS_DEBUG=False
DEBUT=4
FIN=5